### PR TITLE
optional parameters for getURI and static functions

### PR DESCRIPTION
**Pull request by benaryorg**
already tested

### CODE REVIEW

**Comment by stolendata** [comment]
Which TOTP authenticator tool is it that doesn't like the digits and period variables? If anything, they should best be set to a specific default instead of omitted.

**Comment by benaryorg** [comment]
I only know [SailOTP](https://openrepos.net/content/seiichiro0185/sailotp), but there might me more.

Also, the defaults would not be suitable when generating QR-Codes.

The optional arguments still work for everyone, the defaults could be a problem for those not in need for these parameters.

I would suggest making the parameters optional to suit everyone's use case.

**Comment by stolendata** [comment]
But what exactly does SailOTP do when you supply digits/period to it? Ignore them? Behave oddly? If it just ignores them then there is no problem - a larger QR code can at most be considered an inconvenience.

RFC6238 recommends 30 seconds as the default period (Google Authenticator even hardcodes this and ignores the period parameter) but offers no recommendation on the digit count. Since 6 digits is presumed to be the default by everyone I'll go with your suggestion and make the two parameters optional along with some simple format checking.

**Comment by benaryorg** [comment]
SailOTP just ignores the other parameters.

It uses a global progressbar for all keys with a period of 30s and 6 digits for everything.

Thanks for the commit e0364a9277669191c8898a94e79a7abaa9730b44!

**Pull request closed without merging**
